/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as CaIndexRouteImport } from './routes/ca.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EnMediaRouteImport } from './routes/en.media'
import { Route as EnHowItWorksRouteImport } from './routes/en.how-it-works'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnBlogRouteImport } from './routes/en.blog'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as CaMediaRouteImport } from './routes/ca.media'
import { Route as CaHowItWorksRouteImport } from './routes/ca.how-it-works'
import { Route as CaContactRouteImport } from './routes/ca.contact'
import { Route as CaBlogRouteImport } from './routes/ca.blog'
import { Route as CaAboutRouteImport } from './routes/ca.about'
import { Route as AppRentalsRouteImport } from './routes/app.rentals'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppCarnetRouteImport } from './routes/app.carnet'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AdminRentalsRouteImport } from './routes/admin.rentals'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminInvitationsRouteImport } from './routes/admin.invitations'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AdminRentalsIndexRouteImport } from './routes/admin.rentals.index'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminInvitationsRouteImport } from './routes/app.admin.invitations'
import { Route as ApiPublicUploadInviteAvatarRouteImport } from './routes/api.public.upload-invite-avatar'
import { Route as AdminRentalsHistoryRouteImport } from './routes/admin.rentals.history'
import { Route as AdminRentalsCatalogRouteImport } from './routes/admin.rentals.catalog'
import { Route as AdminRentalsActiveRouteImport } from './routes/admin.rentals.active'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaIndexRoute = CaIndexRouteImport.update({
  id: '/ca/',
  path: '/ca/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMediaRoute = EnMediaRouteImport.update({
  id: '/en/media',
  path: '/en/media',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHowItWorksRoute = EnHowItWorksRouteImport.update({
  id: '/en/how-it-works',
  path: '/en/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogRoute = EnBlogRouteImport.update({
  id: '/en/blog',
  path: '/en/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaMediaRoute = CaMediaRouteImport.update({
  id: '/ca/media',
  path: '/ca/media',
  getParentRoute: () => rootRouteImport,
} as any)
const CaHowItWorksRoute = CaHowItWorksRouteImport.update({
  id: '/ca/how-it-works',
  path: '/ca/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CaContactRoute = CaContactRouteImport.update({
  id: '/ca/contact',
  path: '/ca/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaBlogRoute = CaBlogRouteImport.update({
  id: '/ca/blog',
  path: '/ca/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaAboutRoute = CaAboutRouteImport.update({
  id: '/ca/about',
  path: '/ca/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRentalsRoute = AppRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCarnetRoute = AppCarnetRouteImport.update({
  id: '/carnet',
  path: '/carnet',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AdminRentalsRoute = AdminRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AdminRentalsIndexRoute = AdminRentalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRentalsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminInvitationsRoute = AppAdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicUploadInviteAvatarRoute =
  ApiPublicUploadInviteAvatarRouteImport.update({
    id: '/api/public/upload-invite-avatar',
    path: '/api/public/upload-invite-avatar',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRentalsHistoryRoute = AdminRentalsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRentalsRoute,
} as any)
const AdminRentalsCatalogRoute = AdminRentalsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRentalsRoute,
} as any)
const AdminRentalsActiveRoute = AdminRentalsActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AdminRentalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/rentals': typeof AdminRentalsRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/carnet': typeof AppCarnetRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rentals': typeof AppRentalsRoute
  '/ca/about': typeof CaAboutRoute
  '/ca/blog': typeof CaBlogRoute
  '/ca/contact': typeof CaContactRoute
  '/ca/how-it-works': typeof CaHowItWorksRoute
  '/ca/media': typeof CaMediaRoute
  '/en/about': typeof EnAboutRoute
  '/en/blog': typeof EnBlogRoute
  '/en/contact': typeof EnContactRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/media': typeof EnMediaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/ca/': typeof CaIndexRoute
  '/en/': typeof EnIndexRoute
  '/admin/rentals/active': typeof AdminRentalsActiveRoute
  '/admin/rentals/catalog': typeof AdminRentalsCatalogRoute
  '/admin/rentals/history': typeof AdminRentalsHistoryRoute
  '/api/public/upload-invite-avatar': typeof ApiPublicUploadInviteAvatarRoute
  '/app/admin/invitations': typeof AppAdminInvitationsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/admin/rentals/': typeof AdminRentalsIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/members': typeof AdminMembersRoute
  '/app/carnet': typeof AppCarnetRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rentals': typeof AppRentalsRoute
  '/ca/about': typeof CaAboutRoute
  '/ca/blog': typeof CaBlogRoute
  '/ca/contact': typeof CaContactRoute
  '/ca/how-it-works': typeof CaHowItWorksRoute
  '/ca/media': typeof CaMediaRoute
  '/en/about': typeof EnAboutRoute
  '/en/blog': typeof EnBlogRoute
  '/en/contact': typeof EnContactRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/media': typeof EnMediaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/ca': typeof CaIndexRoute
  '/en': typeof EnIndexRoute
  '/admin/rentals/active': typeof AdminRentalsActiveRoute
  '/admin/rentals/catalog': typeof AdminRentalsCatalogRoute
  '/admin/rentals/history': typeof AdminRentalsHistoryRoute
  '/api/public/upload-invite-avatar': typeof ApiPublicUploadInviteAvatarRoute
  '/app/admin/invitations': typeof AppAdminInvitationsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/admin/rentals': typeof AdminRentalsIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/rentals': typeof AdminRentalsRouteWithChildren
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/carnet': typeof AppCarnetRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rentals': typeof AppRentalsRoute
  '/ca/about': typeof CaAboutRoute
  '/ca/blog': typeof CaBlogRoute
  '/ca/contact': typeof CaContactRoute
  '/ca/how-it-works': typeof CaHowItWorksRoute
  '/ca/media': typeof CaMediaRoute
  '/en/about': typeof EnAboutRoute
  '/en/blog': typeof EnBlogRoute
  '/en/contact': typeof EnContactRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/media': typeof EnMediaRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/ca/': typeof CaIndexRoute
  '/en/': typeof EnIndexRoute
  '/admin/rentals/active': typeof AdminRentalsActiveRoute
  '/admin/rentals/catalog': typeof AdminRentalsCatalogRoute
  '/admin/rentals/history': typeof AdminRentalsHistoryRoute
  '/api/public/upload-invite-avatar': typeof ApiPublicUploadInviteAvatarRoute
  '/app/admin/invitations': typeof AppAdminInvitationsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/admin/rentals/': typeof AdminRentalsIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/blog'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/media'
    | '/super-admin'
    | '/admin/content'
    | '/admin/invitations'
    | '/admin/members'
    | '/admin/rentals'
    | '/app/admin'
    | '/app/carnet'
    | '/app/profile'
    | '/app/rentals'
    | '/ca/about'
    | '/ca/blog'
    | '/ca/contact'
    | '/ca/how-it-works'
    | '/ca/media'
    | '/en/about'
    | '/en/blog'
    | '/en/contact'
    | '/en/how-it-works'
    | '/en/media'
    | '/invite/$token'
    | '/admin/'
    | '/app/'
    | '/ca/'
    | '/en/'
    | '/admin/rentals/active'
    | '/admin/rentals/catalog'
    | '/admin/rentals/history'
    | '/api/public/upload-invite-avatar'
    | '/app/admin/invitations'
    | '/app/admin/users'
    | '/admin/rentals/'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/media'
    | '/super-admin'
    | '/admin/content'
    | '/admin/invitations'
    | '/admin/members'
    | '/app/carnet'
    | '/app/profile'
    | '/app/rentals'
    | '/ca/about'
    | '/ca/blog'
    | '/ca/contact'
    | '/ca/how-it-works'
    | '/ca/media'
    | '/en/about'
    | '/en/blog'
    | '/en/contact'
    | '/en/how-it-works'
    | '/en/media'
    | '/invite/$token'
    | '/admin'
    | '/app'
    | '/ca'
    | '/en'
    | '/admin/rentals/active'
    | '/admin/rentals/catalog'
    | '/admin/rentals/history'
    | '/api/public/upload-invite-avatar'
    | '/app/admin/invitations'
    | '/app/admin/users'
    | '/admin/rentals'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/blog'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/media'
    | '/super-admin'
    | '/admin/content'
    | '/admin/invitations'
    | '/admin/members'
    | '/admin/rentals'
    | '/app/admin'
    | '/app/carnet'
    | '/app/profile'
    | '/app/rentals'
    | '/ca/about'
    | '/ca/blog'
    | '/ca/contact'
    | '/ca/how-it-works'
    | '/ca/media'
    | '/en/about'
    | '/en/blog'
    | '/en/contact'
    | '/en/how-it-works'
    | '/en/media'
    | '/invite/$token'
    | '/admin/'
    | '/app/'
    | '/ca/'
    | '/en/'
    | '/admin/rentals/active'
    | '/admin/rentals/catalog'
    | '/admin/rentals/history'
    | '/api/public/upload-invite-avatar'
    | '/app/admin/invitations'
    | '/app/admin/users'
    | '/admin/rentals/'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  SuperAdminRoute: typeof SuperAdminRoute
  CaAboutRoute: typeof CaAboutRoute
  CaBlogRoute: typeof CaBlogRoute
  CaContactRoute: typeof CaContactRoute
  CaHowItWorksRoute: typeof CaHowItWorksRoute
  CaMediaRoute: typeof CaMediaRoute
  EnAboutRoute: typeof EnAboutRoute
  EnBlogRoute: typeof EnBlogRoute
  EnContactRoute: typeof EnContactRoute
  EnHowItWorksRoute: typeof EnHowItWorksRoute
  EnMediaRoute: typeof EnMediaRoute
  InviteTokenRoute: typeof InviteTokenRoute
  CaIndexRoute: typeof CaIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  ApiPublicUploadInviteAvatarRoute: typeof ApiPublicUploadInviteAvatarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/': {
      id: '/ca/'
      path: '/ca'
      fullPath: '/ca/'
      preLoaderRoute: typeof CaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/media': {
      id: '/en/media'
      path: '/en/media'
      fullPath: '/en/media'
      preLoaderRoute: typeof EnMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/how-it-works': {
      id: '/en/how-it-works'
      path: '/en/how-it-works'
      fullPath: '/en/how-it-works'
      preLoaderRoute: typeof EnHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog': {
      id: '/en/blog'
      path: '/en/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof EnBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/media': {
      id: '/ca/media'
      path: '/ca/media'
      fullPath: '/ca/media'
      preLoaderRoute: typeof CaMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/how-it-works': {
      id: '/ca/how-it-works'
      path: '/ca/how-it-works'
      fullPath: '/ca/how-it-works'
      preLoaderRoute: typeof CaHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/contact': {
      id: '/ca/contact'
      path: '/ca/contact'
      fullPath: '/ca/contact'
      preLoaderRoute: typeof CaContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/blog': {
      id: '/ca/blog'
      path: '/ca/blog'
      fullPath: '/ca/blog'
      preLoaderRoute: typeof CaBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/about': {
      id: '/ca/about'
      path: '/ca/about'
      fullPath: '/ca/about'
      preLoaderRoute: typeof CaAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rentals': {
      id: '/app/rentals'
      path: '/rentals'
      fullPath: '/app/rentals'
      preLoaderRoute: typeof AppRentalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carnet': {
      id: '/app/carnet'
      path: '/carnet'
      fullPath: '/app/carnet'
      preLoaderRoute: typeof AppCarnetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/rentals': {
      id: '/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/admin/rentals/': {
      id: '/admin/rentals/'
      path: '/'
      fullPath: '/admin/rentals/'
      preLoaderRoute: typeof AdminRentalsIndexRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/invitations': {
      id: '/app/admin/invitations'
      path: '/invitations'
      fullPath: '/app/admin/invitations'
      preLoaderRoute: typeof AppAdminInvitationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/upload-invite-avatar': {
      id: '/api/public/upload-invite-avatar'
      path: '/api/public/upload-invite-avatar'
      fullPath: '/api/public/upload-invite-avatar'
      preLoaderRoute: typeof ApiPublicUploadInviteAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rentals/history': {
      id: '/admin/rentals/history'
      path: '/history'
      fullPath: '/admin/rentals/history'
      preLoaderRoute: typeof AdminRentalsHistoryRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
    '/admin/rentals/catalog': {
      id: '/admin/rentals/catalog'
      path: '/catalog'
      fullPath: '/admin/rentals/catalog'
      preLoaderRoute: typeof AdminRentalsCatalogRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
    '/admin/rentals/active': {
      id: '/admin/rentals/active'
      path: '/active'
      fullPath: '/admin/rentals/active'
      preLoaderRoute: typeof AdminRentalsActiveRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
  }
}

interface AdminRentalsRouteChildren {
  AdminRentalsActiveRoute: typeof AdminRentalsActiveRoute
  AdminRentalsCatalogRoute: typeof AdminRentalsCatalogRoute
  AdminRentalsHistoryRoute: typeof AdminRentalsHistoryRoute
  AdminRentalsIndexRoute: typeof AdminRentalsIndexRoute
}

const AdminRentalsRouteChildren: AdminRentalsRouteChildren = {
  AdminRentalsActiveRoute: AdminRentalsActiveRoute,
  AdminRentalsCatalogRoute: AdminRentalsCatalogRoute,
  AdminRentalsHistoryRoute: AdminRentalsHistoryRoute,
  AdminRentalsIndexRoute: AdminRentalsIndexRoute,
}

const AdminRentalsRouteWithChildren = AdminRentalsRoute._addFileChildren(
  AdminRentalsRouteChildren,
)

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminInvitationsRoute: typeof AdminInvitationsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminRentalsRoute: typeof AdminRentalsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminInvitationsRoute: AdminInvitationsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminRentalsRoute: AdminRentalsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppAdminRouteChildren {
  AppAdminInvitationsRoute: typeof AppAdminInvitationsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminInvitationsRoute: AppAdminInvitationsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCarnetRoute: typeof AppCarnetRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRentalsRoute: typeof AppRentalsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCarnetRoute: AppCarnetRoute,
  AppProfileRoute: AppProfileRoute,
  AppRentalsRoute: AppRentalsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  SuperAdminRoute: SuperAdminRoute,
  CaAboutRoute: CaAboutRoute,
  CaBlogRoute: CaBlogRoute,
  CaContactRoute: CaContactRoute,
  CaHowItWorksRoute: CaHowItWorksRoute,
  CaMediaRoute: CaMediaRoute,
  EnAboutRoute: EnAboutRoute,
  EnBlogRoute: EnBlogRoute,
  EnContactRoute: EnContactRoute,
  EnHowItWorksRoute: EnHowItWorksRoute,
  EnMediaRoute: EnMediaRoute,
  InviteTokenRoute: InviteTokenRoute,
  CaIndexRoute: CaIndexRoute,
  EnIndexRoute: EnIndexRoute,
  ApiPublicUploadInviteAvatarRoute: ApiPublicUploadInviteAvatarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
