/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneosRouteImport } from './routes/torneos'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as TardaDeJocsICuinaJaponesaRouteImport } from './routes/tarda-de-jocs-i-cuina-japonesa'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RolesOcultosRouteImport } from './routes/roles-ocultos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as MediosRouteImport } from './routes/medios'
import { Route as LudotecaRouteImport } from './routes/ludoteca'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CatanRouteImport } from './routes/catan'
import { Route as BloodOnTheClocktowerRouteImport } from './routes/blood-on-the-clocktower'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as CaIndexRouteImport } from './routes/ca.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InscripcionSlugRouteImport } from './routes/inscripcion.$slug'
import { Route as EnTournamentsRouteImport } from './routes/en.tournaments'
import { Route as EnTermsRouteImport } from './routes/en.terms'
import { Route as EnPrivacyRouteImport } from './routes/en.privacy'
import { Route as EnMediaRouteImport } from './routes/en.media'
import { Route as EnLudotecaRouteImport } from './routes/en.ludoteca'
import { Route as EnLegalNoticeRouteImport } from './routes/en.legal-notice'
import { Route as EnHowItWorksRouteImport } from './routes/en.how-it-works'
import { Route as EnHiddenRolesRouteImport } from './routes/en.hidden-roles'
import { Route as EnCookiesRouteImport } from './routes/en.cookies'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnCatanRouteImport } from './routes/en.catan'
import { Route as EnBloodOnTheClocktowerRouteImport } from './routes/en.blood-on-the-clocktower'
import { Route as EnBlogRouteImport } from './routes/en.blog'
import { Route as EnActivitiesRouteImport } from './routes/en.activities'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as CaTornejosRouteImport } from './routes/ca.tornejos'
import { Route as CaTermesRouteImport } from './routes/ca.termes'
import { Route as CaRolsOcultsRouteImport } from './routes/ca.rols-ocults'
import { Route as CaQuiSomRouteImport } from './routes/ca.qui-som'
import { Route as CaPrivacitatRouteImport } from './routes/ca.privacitat'
import { Route as CaMitjansRouteImport } from './routes/ca.mitjans'
import { Route as CaLudotecaRouteImport } from './routes/ca.ludoteca'
import { Route as CaCookiesRouteImport } from './routes/ca.cookies'
import { Route as CaContacteRouteImport } from './routes/ca.contacte'
import { Route as CaComFuncionaRouteImport } from './routes/ca.com-funciona'
import { Route as CaCatanRouteImport } from './routes/ca.catan'
import { Route as CaBloodOnTheClocktowerRouteImport } from './routes/ca.blood-on-the-clocktower'
import { Route as CaBlogRouteImport } from './routes/ca.blog'
import { Route as CaAvisLegalRouteImport } from './routes/ca.avis-legal'
import { Route as CaActivitatsRouteImport } from './routes/ca.activitats'
import { Route as AppRentalsRouteImport } from './routes/app.rentals'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppCarnetRouteImport } from './routes/app.carnet'
import { Route as AdminRentalsRouteImport } from './routes/admin.rentals'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminInvitationsRouteImport } from './routes/admin.invitations'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminRentalsIndexRouteImport } from './routes/admin.rentals.index'
import { Route as AdminRegistrationsIndexRouteImport } from './routes/admin.registrations.index'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AppRentalsMineRouteImport } from './routes/app.rentals.mine'
import { Route as ApiPublicUploadInviteAvatarRouteImport } from './routes/api.public.upload-invite-avatar'
import { Route as ApiPublicSyncBggRouteImport } from './routes/api.public.sync-bgg'
import { Route as ApiPublicRefreshMediaOgRouteImport } from './routes/api.public.refresh-media-og'
import { Route as AdminRentalsSettingsRouteImport } from './routes/admin.rentals.settings'
import { Route as AdminRentalsHistoryRouteImport } from './routes/admin.rentals.history'
import { Route as AdminRentalsCatalogRouteImport } from './routes/admin.rentals.catalog'
import { Route as AdminRentalsActiveRouteImport } from './routes/admin.rentals.active'
import { Route as AdminRegistrationsIdRouteImport } from './routes/admin.registrations.$id'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin.pages.$pageId'
import { Route as AdminContentUrlsRouteImport } from './routes/admin.content.urls'
import { Route as AdminContentRedirectsRouteImport } from './routes/admin.content.redirects'
import { Route as AdminContentPageKeyRouteImport } from './routes/admin.content.$pageKey'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const TorneosRoute = TorneosRouteImport.update({
  id: '/torneos',
  path: '/torneos',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const TardaDeJocsICuinaJaponesaRoute =
  TardaDeJocsICuinaJaponesaRouteImport.update({
    id: '/tarda-de-jocs-i-cuina-japonesa',
    path: '/tarda-de-jocs-i-cuina-japonesa',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesOcultosRoute = RolesOcultosRouteImport.update({
  id: '/roles-ocultos',
  path: '/roles-ocultos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const MediosRoute = MediosRouteImport.update({
  id: '/medios',
  path: '/medios',
  getParentRoute: () => rootRouteImport,
} as any)
const LudotecaRoute = LudotecaRouteImport.update({
  id: '/ludoteca',
  path: '/ludoteca',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CatanRoute = CatanRouteImport.update({
  id: '/catan',
  path: '/catan',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodOnTheClocktowerRoute = BloodOnTheClocktowerRouteImport.update({
  id: '/blood-on-the-clocktower',
  path: '/blood-on-the-clocktower',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaIndexRoute = CaIndexRouteImport.update({
  id: '/ca/',
  path: '/ca/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionSlugRoute = InscripcionSlugRouteImport.update({
  id: '/inscripcion/$slug',
  path: '/inscripcion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnTournamentsRoute = EnTournamentsRouteImport.update({
  id: '/en/tournaments',
  path: '/en/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/en/terms',
  path: '/en/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/en/privacy',
  path: '/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMediaRoute = EnMediaRouteImport.update({
  id: '/en/media',
  path: '/en/media',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLudotecaRoute = EnLudotecaRouteImport.update({
  id: '/en/ludoteca',
  path: '/en/ludoteca',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLegalNoticeRoute = EnLegalNoticeRouteImport.update({
  id: '/en/legal-notice',
  path: '/en/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHowItWorksRoute = EnHowItWorksRouteImport.update({
  id: '/en/how-it-works',
  path: '/en/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EnHiddenRolesRoute = EnHiddenRolesRouteImport.update({
  id: '/en/hidden-roles',
  path: '/en/hidden-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCookiesRoute = EnCookiesRouteImport.update({
  id: '/en/cookies',
  path: '/en/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCatanRoute = EnCatanRouteImport.update({
  id: '/en/catan',
  path: '/en/catan',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBloodOnTheClocktowerRoute = EnBloodOnTheClocktowerRouteImport.update({
  id: '/en/blood-on-the-clocktower',
  path: '/en/blood-on-the-clocktower',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogRoute = EnBlogRouteImport.update({
  id: '/en/blog',
  path: '/en/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const EnActivitiesRoute = EnActivitiesRouteImport.update({
  id: '/en/activities',
  path: '/en/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaTornejosRoute = CaTornejosRouteImport.update({
  id: '/ca/tornejos',
  path: '/ca/tornejos',
  getParentRoute: () => rootRouteImport,
} as any)
const CaTermesRoute = CaTermesRouteImport.update({
  id: '/ca/termes',
  path: '/ca/termes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaRolsOcultsRoute = CaRolsOcultsRouteImport.update({
  id: '/ca/rols-ocults',
  path: '/ca/rols-ocults',
  getParentRoute: () => rootRouteImport,
} as any)
const CaQuiSomRoute = CaQuiSomRouteImport.update({
  id: '/ca/qui-som',
  path: '/ca/qui-som',
  getParentRoute: () => rootRouteImport,
} as any)
const CaPrivacitatRoute = CaPrivacitatRouteImport.update({
  id: '/ca/privacitat',
  path: '/ca/privacitat',
  getParentRoute: () => rootRouteImport,
} as any)
const CaMitjansRoute = CaMitjansRouteImport.update({
  id: '/ca/mitjans',
  path: '/ca/mitjans',
  getParentRoute: () => rootRouteImport,
} as any)
const CaLudotecaRoute = CaLudotecaRouteImport.update({
  id: '/ca/ludoteca',
  path: '/ca/ludoteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CaCookiesRoute = CaCookiesRouteImport.update({
  id: '/ca/cookies',
  path: '/ca/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CaContacteRoute = CaContacteRouteImport.update({
  id: '/ca/contacte',
  path: '/ca/contacte',
  getParentRoute: () => rootRouteImport,
} as any)
const CaComFuncionaRoute = CaComFuncionaRouteImport.update({
  id: '/ca/com-funciona',
  path: '/ca/com-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CaCatanRoute = CaCatanRouteImport.update({
  id: '/ca/catan',
  path: '/ca/catan',
  getParentRoute: () => rootRouteImport,
} as any)
const CaBloodOnTheClocktowerRoute = CaBloodOnTheClocktowerRouteImport.update({
  id: '/ca/blood-on-the-clocktower',
  path: '/ca/blood-on-the-clocktower',
  getParentRoute: () => rootRouteImport,
} as any)
const CaBlogRoute = CaBlogRouteImport.update({
  id: '/ca/blog',
  path: '/ca/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaAvisLegalRoute = CaAvisLegalRouteImport.update({
  id: '/ca/avis-legal',
  path: '/ca/avis-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CaActivitatsRoute = CaActivitatsRouteImport.update({
  id: '/ca/activitats',
  path: '/ca/activitats',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRentalsRoute = AppRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCarnetRoute = AppCarnetRouteImport.update({
  id: '/carnet',
  path: '/carnet',
  getParentRoute: () => AppRoute,
} as any)
const AdminRentalsRoute = AdminRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalsIndexRoute = AdminRentalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRentalsRoute,
} as any)
const AdminRegistrationsIndexRoute = AdminRegistrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRegistrationsRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AppRentalsMineRoute = AppRentalsMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AppRentalsRoute,
} as any)
const ApiPublicUploadInviteAvatarRoute =
  ApiPublicUploadInviteAvatarRouteImport.update({
    id: '/api/public/upload-invite-avatar',
    path: '/api/public/upload-invite-avatar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncBggRoute = ApiPublicSyncBggRouteImport.update({
  id: '/api/public/sync-bgg',
  path: '/api/public/sync-bgg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshMediaOgRoute = ApiPublicRefreshMediaOgRouteImport.update({
  id: '/api/public/refresh-media-og',
  path: '/api/public/refresh-media-og',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRentalsSettingsRoute = AdminRentalsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRentalsRoute,
} as any)
const AdminRentalsHistoryRoute = AdminRentalsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRentalsRoute,
} as any)
const AdminRentalsCatalogRoute = AdminRentalsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRentalsRoute,
} as any)
const AdminRentalsActiveRoute = AdminRentalsActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AdminRentalsRoute,
} as any)
const AdminRegistrationsIdRoute = AdminRegistrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRegistrationsRoute,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentUrlsRoute = AdminContentUrlsRouteImport.update({
  id: '/urls',
  path: '/urls',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentRedirectsRoute = AdminContentRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentPageKeyRoute = AdminContentPageKeyRouteImport.update({
  id: '/$pageKey',
  path: '/$pageKey',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/actividades': typeof ActividadesRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/blood-on-the-clocktower': typeof BloodOnTheClocktowerRoute
  '/catan': typeof CatanRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/ludoteca': typeof LudotecaRoute
  '/medios': typeof MediosRoute
  '/privacidad': typeof PrivacidadRoute
  '/roles-ocultos': typeof RolesOcultosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarda-de-jocs-i-cuina-japonesa': typeof TardaDeJocsICuinaJaponesaRoute
  '/terminos': typeof TerminosRoute
  '/torneos': typeof TorneosRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/registrations': typeof AdminRegistrationsRouteWithChildren
  '/admin/rentals': typeof AdminRentalsRouteWithChildren
  '/app/carnet': typeof AppCarnetRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rentals': typeof AppRentalsRouteWithChildren
  '/ca/activitats': typeof CaActivitatsRoute
  '/ca/avis-legal': typeof CaAvisLegalRoute
  '/ca/blog': typeof CaBlogRoute
  '/ca/blood-on-the-clocktower': typeof CaBloodOnTheClocktowerRoute
  '/ca/catan': typeof CaCatanRoute
  '/ca/com-funciona': typeof CaComFuncionaRoute
  '/ca/contacte': typeof CaContacteRoute
  '/ca/cookies': typeof CaCookiesRoute
  '/ca/ludoteca': typeof CaLudotecaRoute
  '/ca/mitjans': typeof CaMitjansRoute
  '/ca/privacitat': typeof CaPrivacitatRoute
  '/ca/qui-som': typeof CaQuiSomRoute
  '/ca/rols-ocults': typeof CaRolsOcultsRoute
  '/ca/termes': typeof CaTermesRoute
  '/ca/tornejos': typeof CaTornejosRoute
  '/en/about': typeof EnAboutRoute
  '/en/activities': typeof EnActivitiesRoute
  '/en/blog': typeof EnBlogRoute
  '/en/blood-on-the-clocktower': typeof EnBloodOnTheClocktowerRoute
  '/en/catan': typeof EnCatanRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookies': typeof EnCookiesRoute
  '/en/hidden-roles': typeof EnHiddenRolesRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/legal-notice': typeof EnLegalNoticeRoute
  '/en/ludoteca': typeof EnLudotecaRoute
  '/en/media': typeof EnMediaRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/en/tournaments': typeof EnTournamentsRoute
  '/inscripcion/$slug': typeof InscripcionSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/ca/': typeof CaIndexRoute
  '/en/': typeof EnIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/content/$pageKey': typeof AdminContentPageKeyRoute
  '/admin/content/redirects': typeof AdminContentRedirectsRoute
  '/admin/content/urls': typeof AdminContentUrlsRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/rentals/active': typeof AdminRentalsActiveRoute
  '/admin/rentals/catalog': typeof AdminRentalsCatalogRoute
  '/admin/rentals/history': typeof AdminRentalsHistoryRoute
  '/admin/rentals/settings': typeof AdminRentalsSettingsRoute
  '/api/public/refresh-media-og': typeof ApiPublicRefreshMediaOgRoute
  '/api/public/sync-bgg': typeof ApiPublicSyncBggRoute
  '/api/public/upload-invite-avatar': typeof ApiPublicUploadInviteAvatarRoute
  '/app/rentals/mine': typeof AppRentalsMineRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/registrations/': typeof AdminRegistrationsIndexRoute
  '/admin/rentals/': typeof AdminRentalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/actividades': typeof ActividadesRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/blood-on-the-clocktower': typeof BloodOnTheClocktowerRoute
  '/catan': typeof CatanRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/ludoteca': typeof LudotecaRoute
  '/medios': typeof MediosRoute
  '/privacidad': typeof PrivacidadRoute
  '/roles-ocultos': typeof RolesOcultosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarda-de-jocs-i-cuina-japonesa': typeof TardaDeJocsICuinaJaponesaRoute
  '/terminos': typeof TerminosRoute
  '/torneos': typeof TorneosRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/members': typeof AdminMembersRoute
  '/app/carnet': typeof AppCarnetRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rentals': typeof AppRentalsRouteWithChildren
  '/ca/activitats': typeof CaActivitatsRoute
  '/ca/avis-legal': typeof CaAvisLegalRoute
  '/ca/blog': typeof CaBlogRoute
  '/ca/blood-on-the-clocktower': typeof CaBloodOnTheClocktowerRoute
  '/ca/catan': typeof CaCatanRoute
  '/ca/com-funciona': typeof CaComFuncionaRoute
  '/ca/contacte': typeof CaContacteRoute
  '/ca/cookies': typeof CaCookiesRoute
  '/ca/ludoteca': typeof CaLudotecaRoute
  '/ca/mitjans': typeof CaMitjansRoute
  '/ca/privacitat': typeof CaPrivacitatRoute
  '/ca/qui-som': typeof CaQuiSomRoute
  '/ca/rols-ocults': typeof CaRolsOcultsRoute
  '/ca/termes': typeof CaTermesRoute
  '/ca/tornejos': typeof CaTornejosRoute
  '/en/about': typeof EnAboutRoute
  '/en/activities': typeof EnActivitiesRoute
  '/en/blog': typeof EnBlogRoute
  '/en/blood-on-the-clocktower': typeof EnBloodOnTheClocktowerRoute
  '/en/catan': typeof EnCatanRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookies': typeof EnCookiesRoute
  '/en/hidden-roles': typeof EnHiddenRolesRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/legal-notice': typeof EnLegalNoticeRoute
  '/en/ludoteca': typeof EnLudotecaRoute
  '/en/media': typeof EnMediaRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/en/tournaments': typeof EnTournamentsRoute
  '/inscripcion/$slug': typeof InscripcionSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/ca': typeof CaIndexRoute
  '/en': typeof EnIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/content/$pageKey': typeof AdminContentPageKeyRoute
  '/admin/content/redirects': typeof AdminContentRedirectsRoute
  '/admin/content/urls': typeof AdminContentUrlsRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/rentals/active': typeof AdminRentalsActiveRoute
  '/admin/rentals/catalog': typeof AdminRentalsCatalogRoute
  '/admin/rentals/history': typeof AdminRentalsHistoryRoute
  '/admin/rentals/settings': typeof AdminRentalsSettingsRoute
  '/api/public/refresh-media-og': typeof ApiPublicRefreshMediaOgRoute
  '/api/public/sync-bgg': typeof ApiPublicSyncBggRoute
  '/api/public/upload-invite-avatar': typeof ApiPublicUploadInviteAvatarRoute
  '/app/rentals/mine': typeof AppRentalsMineRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/registrations': typeof AdminRegistrationsIndexRoute
  '/admin/rentals': typeof AdminRentalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/actividades': typeof ActividadesRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRoute
  '/blood-on-the-clocktower': typeof BloodOnTheClocktowerRoute
  '/catan': typeof CatanRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/ludoteca': typeof LudotecaRoute
  '/medios': typeof MediosRoute
  '/privacidad': typeof PrivacidadRoute
  '/roles-ocultos': typeof RolesOcultosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/super-admin': typeof SuperAdminRoute
  '/tarda-de-jocs-i-cuina-japonesa': typeof TardaDeJocsICuinaJaponesaRoute
  '/terminos': typeof TerminosRoute
  '/torneos': typeof TorneosRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/registrations': typeof AdminRegistrationsRouteWithChildren
  '/admin/rentals': typeof AdminRentalsRouteWithChildren
  '/app/carnet': typeof AppCarnetRoute
  '/app/profile': typeof AppProfileRoute
  '/app/rentals': typeof AppRentalsRouteWithChildren
  '/ca/activitats': typeof CaActivitatsRoute
  '/ca/avis-legal': typeof CaAvisLegalRoute
  '/ca/blog': typeof CaBlogRoute
  '/ca/blood-on-the-clocktower': typeof CaBloodOnTheClocktowerRoute
  '/ca/catan': typeof CaCatanRoute
  '/ca/com-funciona': typeof CaComFuncionaRoute
  '/ca/contacte': typeof CaContacteRoute
  '/ca/cookies': typeof CaCookiesRoute
  '/ca/ludoteca': typeof CaLudotecaRoute
  '/ca/mitjans': typeof CaMitjansRoute
  '/ca/privacitat': typeof CaPrivacitatRoute
  '/ca/qui-som': typeof CaQuiSomRoute
  '/ca/rols-ocults': typeof CaRolsOcultsRoute
  '/ca/termes': typeof CaTermesRoute
  '/ca/tornejos': typeof CaTornejosRoute
  '/en/about': typeof EnAboutRoute
  '/en/activities': typeof EnActivitiesRoute
  '/en/blog': typeof EnBlogRoute
  '/en/blood-on-the-clocktower': typeof EnBloodOnTheClocktowerRoute
  '/en/catan': typeof EnCatanRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookies': typeof EnCookiesRoute
  '/en/hidden-roles': typeof EnHiddenRolesRoute
  '/en/how-it-works': typeof EnHowItWorksRoute
  '/en/legal-notice': typeof EnLegalNoticeRoute
  '/en/ludoteca': typeof EnLudotecaRoute
  '/en/media': typeof EnMediaRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/en/tournaments': typeof EnTournamentsRoute
  '/inscripcion/$slug': typeof InscripcionSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/ca/': typeof CaIndexRoute
  '/en/': typeof EnIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/content/$pageKey': typeof AdminContentPageKeyRoute
  '/admin/content/redirects': typeof AdminContentRedirectsRoute
  '/admin/content/urls': typeof AdminContentUrlsRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/registrations/$id': typeof AdminRegistrationsIdRoute
  '/admin/rentals/active': typeof AdminRentalsActiveRoute
  '/admin/rentals/catalog': typeof AdminRentalsCatalogRoute
  '/admin/rentals/history': typeof AdminRentalsHistoryRoute
  '/admin/rentals/settings': typeof AdminRentalsSettingsRoute
  '/api/public/refresh-media-og': typeof ApiPublicRefreshMediaOgRoute
  '/api/public/sync-bgg': typeof ApiPublicSyncBggRoute
  '/api/public/upload-invite-avatar': typeof ApiPublicUploadInviteAvatarRoute
  '/app/rentals/mine': typeof AppRentalsMineRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/registrations/': typeof AdminRegistrationsIndexRoute
  '/admin/rentals/': typeof AdminRentalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/actividades'
    | '/admin'
    | '/app'
    | '/aviso-legal'
    | '/blog'
    | '/blood-on-the-clocktower'
    | '/catan'
    | '/como-funciona'
    | '/contacto'
    | '/cookies'
    | '/login'
    | '/ludoteca'
    | '/medios'
    | '/privacidad'
    | '/roles-ocultos'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/super-admin'
    | '/tarda-de-jocs-i-cuina-japonesa'
    | '/terminos'
    | '/torneos'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/invitations'
    | '/admin/members'
    | '/admin/registrations'
    | '/admin/rentals'
    | '/app/carnet'
    | '/app/profile'
    | '/app/rentals'
    | '/ca/activitats'
    | '/ca/avis-legal'
    | '/ca/blog'
    | '/ca/blood-on-the-clocktower'
    | '/ca/catan'
    | '/ca/com-funciona'
    | '/ca/contacte'
    | '/ca/cookies'
    | '/ca/ludoteca'
    | '/ca/mitjans'
    | '/ca/privacitat'
    | '/ca/qui-som'
    | '/ca/rols-ocults'
    | '/ca/termes'
    | '/ca/tornejos'
    | '/en/about'
    | '/en/activities'
    | '/en/blog'
    | '/en/blood-on-the-clocktower'
    | '/en/catan'
    | '/en/contact'
    | '/en/cookies'
    | '/en/hidden-roles'
    | '/en/how-it-works'
    | '/en/legal-notice'
    | '/en/ludoteca'
    | '/en/media'
    | '/en/privacy'
    | '/en/terms'
    | '/en/tournaments'
    | '/inscripcion/$slug'
    | '/invite/$token'
    | '/admin/'
    | '/app/'
    | '/ca/'
    | '/en/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/content/$pageKey'
    | '/admin/content/redirects'
    | '/admin/content/urls'
    | '/admin/pages/$pageId'
    | '/admin/registrations/$id'
    | '/admin/rentals/active'
    | '/admin/rentals/catalog'
    | '/admin/rentals/history'
    | '/admin/rentals/settings'
    | '/api/public/refresh-media-og'
    | '/api/public/sync-bgg'
    | '/api/public/upload-invite-avatar'
    | '/app/rentals/mine'
    | '/admin/blog/'
    | '/admin/content/'
    | '/admin/registrations/'
    | '/admin/rentals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/actividades'
    | '/aviso-legal'
    | '/blog'
    | '/blood-on-the-clocktower'
    | '/catan'
    | '/como-funciona'
    | '/contacto'
    | '/cookies'
    | '/login'
    | '/ludoteca'
    | '/medios'
    | '/privacidad'
    | '/roles-ocultos'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/super-admin'
    | '/tarda-de-jocs-i-cuina-japonesa'
    | '/terminos'
    | '/torneos'
    | '/admin/invitations'
    | '/admin/members'
    | '/app/carnet'
    | '/app/profile'
    | '/app/rentals'
    | '/ca/activitats'
    | '/ca/avis-legal'
    | '/ca/blog'
    | '/ca/blood-on-the-clocktower'
    | '/ca/catan'
    | '/ca/com-funciona'
    | '/ca/contacte'
    | '/ca/cookies'
    | '/ca/ludoteca'
    | '/ca/mitjans'
    | '/ca/privacitat'
    | '/ca/qui-som'
    | '/ca/rols-ocults'
    | '/ca/termes'
    | '/ca/tornejos'
    | '/en/about'
    | '/en/activities'
    | '/en/blog'
    | '/en/blood-on-the-clocktower'
    | '/en/catan'
    | '/en/contact'
    | '/en/cookies'
    | '/en/hidden-roles'
    | '/en/how-it-works'
    | '/en/legal-notice'
    | '/en/ludoteca'
    | '/en/media'
    | '/en/privacy'
    | '/en/terms'
    | '/en/tournaments'
    | '/inscripcion/$slug'
    | '/invite/$token'
    | '/admin'
    | '/app'
    | '/ca'
    | '/en'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/content/$pageKey'
    | '/admin/content/redirects'
    | '/admin/content/urls'
    | '/admin/pages/$pageId'
    | '/admin/registrations/$id'
    | '/admin/rentals/active'
    | '/admin/rentals/catalog'
    | '/admin/rentals/history'
    | '/admin/rentals/settings'
    | '/api/public/refresh-media-og'
    | '/api/public/sync-bgg'
    | '/api/public/upload-invite-avatar'
    | '/app/rentals/mine'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/registrations'
    | '/admin/rentals'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/actividades'
    | '/admin'
    | '/app'
    | '/aviso-legal'
    | '/blog'
    | '/blood-on-the-clocktower'
    | '/catan'
    | '/como-funciona'
    | '/contacto'
    | '/cookies'
    | '/login'
    | '/ludoteca'
    | '/medios'
    | '/privacidad'
    | '/roles-ocultos'
    | '/sitemap.xml'
    | '/sobre-nosotros'
    | '/super-admin'
    | '/tarda-de-jocs-i-cuina-japonesa'
    | '/terminos'
    | '/torneos'
    | '/admin/blog'
    | '/admin/content'
    | '/admin/invitations'
    | '/admin/members'
    | '/admin/registrations'
    | '/admin/rentals'
    | '/app/carnet'
    | '/app/profile'
    | '/app/rentals'
    | '/ca/activitats'
    | '/ca/avis-legal'
    | '/ca/blog'
    | '/ca/blood-on-the-clocktower'
    | '/ca/catan'
    | '/ca/com-funciona'
    | '/ca/contacte'
    | '/ca/cookies'
    | '/ca/ludoteca'
    | '/ca/mitjans'
    | '/ca/privacitat'
    | '/ca/qui-som'
    | '/ca/rols-ocults'
    | '/ca/termes'
    | '/ca/tornejos'
    | '/en/about'
    | '/en/activities'
    | '/en/blog'
    | '/en/blood-on-the-clocktower'
    | '/en/catan'
    | '/en/contact'
    | '/en/cookies'
    | '/en/hidden-roles'
    | '/en/how-it-works'
    | '/en/legal-notice'
    | '/en/ludoteca'
    | '/en/media'
    | '/en/privacy'
    | '/en/terms'
    | '/en/tournaments'
    | '/inscripcion/$slug'
    | '/invite/$token'
    | '/admin/'
    | '/app/'
    | '/ca/'
    | '/en/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/content/$pageKey'
    | '/admin/content/redirects'
    | '/admin/content/urls'
    | '/admin/pages/$pageId'
    | '/admin/registrations/$id'
    | '/admin/rentals/active'
    | '/admin/rentals/catalog'
    | '/admin/rentals/history'
    | '/admin/rentals/settings'
    | '/api/public/refresh-media-og'
    | '/api/public/sync-bgg'
    | '/api/public/upload-invite-avatar'
    | '/app/rentals/mine'
    | '/admin/blog/'
    | '/admin/content/'
    | '/admin/registrations/'
    | '/admin/rentals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ActividadesRoute: typeof ActividadesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AvisoLegalRoute: typeof AvisoLegalRoute
  BlogRoute: typeof BlogRoute
  BloodOnTheClocktowerRoute: typeof BloodOnTheClocktowerRoute
  CatanRoute: typeof CatanRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  LudotecaRoute: typeof LudotecaRoute
  MediosRoute: typeof MediosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RolesOcultosRoute: typeof RolesOcultosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TardaDeJocsICuinaJaponesaRoute: typeof TardaDeJocsICuinaJaponesaRoute
  TerminosRoute: typeof TerminosRoute
  TorneosRoute: typeof TorneosRoute
  CaActivitatsRoute: typeof CaActivitatsRoute
  CaAvisLegalRoute: typeof CaAvisLegalRoute
  CaBlogRoute: typeof CaBlogRoute
  CaBloodOnTheClocktowerRoute: typeof CaBloodOnTheClocktowerRoute
  CaCatanRoute: typeof CaCatanRoute
  CaComFuncionaRoute: typeof CaComFuncionaRoute
  CaContacteRoute: typeof CaContacteRoute
  CaCookiesRoute: typeof CaCookiesRoute
  CaLudotecaRoute: typeof CaLudotecaRoute
  CaMitjansRoute: typeof CaMitjansRoute
  CaPrivacitatRoute: typeof CaPrivacitatRoute
  CaQuiSomRoute: typeof CaQuiSomRoute
  CaRolsOcultsRoute: typeof CaRolsOcultsRoute
  CaTermesRoute: typeof CaTermesRoute
  CaTornejosRoute: typeof CaTornejosRoute
  EnAboutRoute: typeof EnAboutRoute
  EnActivitiesRoute: typeof EnActivitiesRoute
  EnBlogRoute: typeof EnBlogRoute
  EnBloodOnTheClocktowerRoute: typeof EnBloodOnTheClocktowerRoute
  EnCatanRoute: typeof EnCatanRoute
  EnContactRoute: typeof EnContactRoute
  EnCookiesRoute: typeof EnCookiesRoute
  EnHiddenRolesRoute: typeof EnHiddenRolesRoute
  EnHowItWorksRoute: typeof EnHowItWorksRoute
  EnLegalNoticeRoute: typeof EnLegalNoticeRoute
  EnLudotecaRoute: typeof EnLudotecaRoute
  EnMediaRoute: typeof EnMediaRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnTermsRoute: typeof EnTermsRoute
  EnTournamentsRoute: typeof EnTournamentsRoute
  InscripcionSlugRoute: typeof InscripcionSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  CaIndexRoute: typeof CaIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  ApiPublicRefreshMediaOgRoute: typeof ApiPublicRefreshMediaOgRoute
  ApiPublicSyncBggRoute: typeof ApiPublicSyncBggRoute
  ApiPublicUploadInviteAvatarRoute: typeof ApiPublicUploadInviteAvatarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneos': {
      id: '/torneos'
      path: '/torneos'
      fullPath: '/torneos'
      preLoaderRoute: typeof TorneosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarda-de-jocs-i-cuina-japonesa': {
      id: '/tarda-de-jocs-i-cuina-japonesa'
      path: '/tarda-de-jocs-i-cuina-japonesa'
      fullPath: '/tarda-de-jocs-i-cuina-japonesa'
      preLoaderRoute: typeof TardaDeJocsICuinaJaponesaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles-ocultos': {
      id: '/roles-ocultos'
      path: '/roles-ocultos'
      fullPath: '/roles-ocultos'
      preLoaderRoute: typeof RolesOcultosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medios': {
      id: '/medios'
      path: '/medios'
      fullPath: '/medios'
      preLoaderRoute: typeof MediosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ludoteca': {
      id: '/ludoteca'
      path: '/ludoteca'
      fullPath: '/ludoteca'
      preLoaderRoute: typeof LudotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catan': {
      id: '/catan'
      path: '/catan'
      fullPath: '/catan'
      preLoaderRoute: typeof CatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood-on-the-clocktower': {
      id: '/blood-on-the-clocktower'
      path: '/blood-on-the-clocktower'
      fullPath: '/blood-on-the-clocktower'
      preLoaderRoute: typeof BloodOnTheClocktowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/': {
      id: '/ca/'
      path: '/ca'
      fullPath: '/ca/'
      preLoaderRoute: typeof CaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripcion/$slug': {
      id: '/inscripcion/$slug'
      path: '/inscripcion/$slug'
      fullPath: '/inscripcion/$slug'
      preLoaderRoute: typeof InscripcionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/tournaments': {
      id: '/en/tournaments'
      path: '/en/tournaments'
      fullPath: '/en/tournaments'
      preLoaderRoute: typeof EnTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/en/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/en/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/media': {
      id: '/en/media'
      path: '/en/media'
      fullPath: '/en/media'
      preLoaderRoute: typeof EnMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/ludoteca': {
      id: '/en/ludoteca'
      path: '/en/ludoteca'
      fullPath: '/en/ludoteca'
      preLoaderRoute: typeof EnLudotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/legal-notice': {
      id: '/en/legal-notice'
      path: '/en/legal-notice'
      fullPath: '/en/legal-notice'
      preLoaderRoute: typeof EnLegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/how-it-works': {
      id: '/en/how-it-works'
      path: '/en/how-it-works'
      fullPath: '/en/how-it-works'
      preLoaderRoute: typeof EnHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/hidden-roles': {
      id: '/en/hidden-roles'
      path: '/en/hidden-roles'
      fullPath: '/en/hidden-roles'
      preLoaderRoute: typeof EnHiddenRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/cookies': {
      id: '/en/cookies'
      path: '/en/cookies'
      fullPath: '/en/cookies'
      preLoaderRoute: typeof EnCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/catan': {
      id: '/en/catan'
      path: '/en/catan'
      fullPath: '/en/catan'
      preLoaderRoute: typeof EnCatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blood-on-the-clocktower': {
      id: '/en/blood-on-the-clocktower'
      path: '/en/blood-on-the-clocktower'
      fullPath: '/en/blood-on-the-clocktower'
      preLoaderRoute: typeof EnBloodOnTheClocktowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog': {
      id: '/en/blog'
      path: '/en/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof EnBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/activities': {
      id: '/en/activities'
      path: '/en/activities'
      fullPath: '/en/activities'
      preLoaderRoute: typeof EnActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/tornejos': {
      id: '/ca/tornejos'
      path: '/ca/tornejos'
      fullPath: '/ca/tornejos'
      preLoaderRoute: typeof CaTornejosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/termes': {
      id: '/ca/termes'
      path: '/ca/termes'
      fullPath: '/ca/termes'
      preLoaderRoute: typeof CaTermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/rols-ocults': {
      id: '/ca/rols-ocults'
      path: '/ca/rols-ocults'
      fullPath: '/ca/rols-ocults'
      preLoaderRoute: typeof CaRolsOcultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/qui-som': {
      id: '/ca/qui-som'
      path: '/ca/qui-som'
      fullPath: '/ca/qui-som'
      preLoaderRoute: typeof CaQuiSomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/privacitat': {
      id: '/ca/privacitat'
      path: '/ca/privacitat'
      fullPath: '/ca/privacitat'
      preLoaderRoute: typeof CaPrivacitatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/mitjans': {
      id: '/ca/mitjans'
      path: '/ca/mitjans'
      fullPath: '/ca/mitjans'
      preLoaderRoute: typeof CaMitjansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/ludoteca': {
      id: '/ca/ludoteca'
      path: '/ca/ludoteca'
      fullPath: '/ca/ludoteca'
      preLoaderRoute: typeof CaLudotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/cookies': {
      id: '/ca/cookies'
      path: '/ca/cookies'
      fullPath: '/ca/cookies'
      preLoaderRoute: typeof CaCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/contacte': {
      id: '/ca/contacte'
      path: '/ca/contacte'
      fullPath: '/ca/contacte'
      preLoaderRoute: typeof CaContacteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/com-funciona': {
      id: '/ca/com-funciona'
      path: '/ca/com-funciona'
      fullPath: '/ca/com-funciona'
      preLoaderRoute: typeof CaComFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/catan': {
      id: '/ca/catan'
      path: '/ca/catan'
      fullPath: '/ca/catan'
      preLoaderRoute: typeof CaCatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/blood-on-the-clocktower': {
      id: '/ca/blood-on-the-clocktower'
      path: '/ca/blood-on-the-clocktower'
      fullPath: '/ca/blood-on-the-clocktower'
      preLoaderRoute: typeof CaBloodOnTheClocktowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/blog': {
      id: '/ca/blog'
      path: '/ca/blog'
      fullPath: '/ca/blog'
      preLoaderRoute: typeof CaBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/avis-legal': {
      id: '/ca/avis-legal'
      path: '/ca/avis-legal'
      fullPath: '/ca/avis-legal'
      preLoaderRoute: typeof CaAvisLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca/activitats': {
      id: '/ca/activitats'
      path: '/ca/activitats'
      fullPath: '/ca/activitats'
      preLoaderRoute: typeof CaActivitatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rentals': {
      id: '/app/rentals'
      path: '/rentals'
      fullPath: '/app/rentals'
      preLoaderRoute: typeof AppRentalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carnet': {
      id: '/app/carnet'
      path: '/carnet'
      fullPath: '/app/carnet'
      preLoaderRoute: typeof AppCarnetRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/rentals': {
      id: '/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rentals/': {
      id: '/admin/rentals/'
      path: '/'
      fullPath: '/admin/rentals/'
      preLoaderRoute: typeof AdminRentalsIndexRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
    '/admin/registrations/': {
      id: '/admin/registrations/'
      path: '/'
      fullPath: '/admin/registrations/'
      preLoaderRoute: typeof AdminRegistrationsIndexRouteImport
      parentRoute: typeof AdminRegistrationsRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/app/rentals/mine': {
      id: '/app/rentals/mine'
      path: '/mine'
      fullPath: '/app/rentals/mine'
      preLoaderRoute: typeof AppRentalsMineRouteImport
      parentRoute: typeof AppRentalsRoute
    }
    '/api/public/upload-invite-avatar': {
      id: '/api/public/upload-invite-avatar'
      path: '/api/public/upload-invite-avatar'
      fullPath: '/api/public/upload-invite-avatar'
      preLoaderRoute: typeof ApiPublicUploadInviteAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-bgg': {
      id: '/api/public/sync-bgg'
      path: '/api/public/sync-bgg'
      fullPath: '/api/public/sync-bgg'
      preLoaderRoute: typeof ApiPublicSyncBggRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-media-og': {
      id: '/api/public/refresh-media-og'
      path: '/api/public/refresh-media-og'
      fullPath: '/api/public/refresh-media-og'
      preLoaderRoute: typeof ApiPublicRefreshMediaOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rentals/settings': {
      id: '/admin/rentals/settings'
      path: '/settings'
      fullPath: '/admin/rentals/settings'
      preLoaderRoute: typeof AdminRentalsSettingsRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
    '/admin/rentals/history': {
      id: '/admin/rentals/history'
      path: '/history'
      fullPath: '/admin/rentals/history'
      preLoaderRoute: typeof AdminRentalsHistoryRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
    '/admin/rentals/catalog': {
      id: '/admin/rentals/catalog'
      path: '/catalog'
      fullPath: '/admin/rentals/catalog'
      preLoaderRoute: typeof AdminRentalsCatalogRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
    '/admin/rentals/active': {
      id: '/admin/rentals/active'
      path: '/active'
      fullPath: '/admin/rentals/active'
      preLoaderRoute: typeof AdminRentalsActiveRouteImport
      parentRoute: typeof AdminRentalsRoute
    }
    '/admin/registrations/$id': {
      id: '/admin/registrations/$id'
      path: '/$id'
      fullPath: '/admin/registrations/$id'
      preLoaderRoute: typeof AdminRegistrationsIdRouteImport
      parentRoute: typeof AdminRegistrationsRoute
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/urls': {
      id: '/admin/content/urls'
      path: '/urls'
      fullPath: '/admin/content/urls'
      preLoaderRoute: typeof AdminContentUrlsRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/redirects': {
      id: '/admin/content/redirects'
      path: '/redirects'
      fullPath: '/admin/content/redirects'
      preLoaderRoute: typeof AdminContentRedirectsRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/$pageKey': {
      id: '/admin/content/$pageKey'
      path: '/$pageKey'
      fullPath: '/admin/content/$pageKey'
      preLoaderRoute: typeof AdminContentPageKeyRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminContentRouteChildren {
  AdminContentPageKeyRoute: typeof AdminContentPageKeyRoute
  AdminContentRedirectsRoute: typeof AdminContentRedirectsRoute
  AdminContentUrlsRoute: typeof AdminContentUrlsRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
}

const AdminContentRouteChildren: AdminContentRouteChildren = {
  AdminContentPageKeyRoute: AdminContentPageKeyRoute,
  AdminContentRedirectsRoute: AdminContentRedirectsRoute,
  AdminContentUrlsRoute: AdminContentUrlsRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
}

const AdminContentRouteWithChildren = AdminContentRoute._addFileChildren(
  AdminContentRouteChildren,
)

interface AdminRegistrationsRouteChildren {
  AdminRegistrationsIdRoute: typeof AdminRegistrationsIdRoute
  AdminRegistrationsIndexRoute: typeof AdminRegistrationsIndexRoute
}

const AdminRegistrationsRouteChildren: AdminRegistrationsRouteChildren = {
  AdminRegistrationsIdRoute: AdminRegistrationsIdRoute,
  AdminRegistrationsIndexRoute: AdminRegistrationsIndexRoute,
}

const AdminRegistrationsRouteWithChildren =
  AdminRegistrationsRoute._addFileChildren(AdminRegistrationsRouteChildren)

interface AdminRentalsRouteChildren {
  AdminRentalsActiveRoute: typeof AdminRentalsActiveRoute
  AdminRentalsCatalogRoute: typeof AdminRentalsCatalogRoute
  AdminRentalsHistoryRoute: typeof AdminRentalsHistoryRoute
  AdminRentalsSettingsRoute: typeof AdminRentalsSettingsRoute
  AdminRentalsIndexRoute: typeof AdminRentalsIndexRoute
}

const AdminRentalsRouteChildren: AdminRentalsRouteChildren = {
  AdminRentalsActiveRoute: AdminRentalsActiveRoute,
  AdminRentalsCatalogRoute: AdminRentalsCatalogRoute,
  AdminRentalsHistoryRoute: AdminRentalsHistoryRoute,
  AdminRentalsSettingsRoute: AdminRentalsSettingsRoute,
  AdminRentalsIndexRoute: AdminRentalsIndexRoute,
}

const AdminRentalsRouteWithChildren = AdminRentalsRoute._addFileChildren(
  AdminRentalsRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminContentRoute: typeof AdminContentRouteWithChildren
  AdminInvitationsRoute: typeof AdminInvitationsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRouteWithChildren
  AdminRentalsRoute: typeof AdminRentalsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminContentRoute: AdminContentRouteWithChildren,
  AdminInvitationsRoute: AdminInvitationsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminRegistrationsRoute: AdminRegistrationsRouteWithChildren,
  AdminRentalsRoute: AdminRentalsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRentalsRouteChildren {
  AppRentalsMineRoute: typeof AppRentalsMineRoute
}

const AppRentalsRouteChildren: AppRentalsRouteChildren = {
  AppRentalsMineRoute: AppRentalsMineRoute,
}

const AppRentalsRouteWithChildren = AppRentalsRoute._addFileChildren(
  AppRentalsRouteChildren,
)

interface AppRouteChildren {
  AppCarnetRoute: typeof AppCarnetRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRentalsRoute: typeof AppRentalsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCarnetRoute: AppCarnetRoute,
  AppProfileRoute: AppProfileRoute,
  AppRentalsRoute: AppRentalsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ActividadesRoute: ActividadesRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AvisoLegalRoute: AvisoLegalRoute,
  BlogRoute: BlogRoute,
  BloodOnTheClocktowerRoute: BloodOnTheClocktowerRoute,
  CatanRoute: CatanRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  LudotecaRoute: LudotecaRoute,
  MediosRoute: MediosRoute,
  PrivacidadRoute: PrivacidadRoute,
  RolesOcultosRoute: RolesOcultosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  SuperAdminRoute: SuperAdminRoute,
  TardaDeJocsICuinaJaponesaRoute: TardaDeJocsICuinaJaponesaRoute,
  TerminosRoute: TerminosRoute,
  TorneosRoute: TorneosRoute,
  CaActivitatsRoute: CaActivitatsRoute,
  CaAvisLegalRoute: CaAvisLegalRoute,
  CaBlogRoute: CaBlogRoute,
  CaBloodOnTheClocktowerRoute: CaBloodOnTheClocktowerRoute,
  CaCatanRoute: CaCatanRoute,
  CaComFuncionaRoute: CaComFuncionaRoute,
  CaContacteRoute: CaContacteRoute,
  CaCookiesRoute: CaCookiesRoute,
  CaLudotecaRoute: CaLudotecaRoute,
  CaMitjansRoute: CaMitjansRoute,
  CaPrivacitatRoute: CaPrivacitatRoute,
  CaQuiSomRoute: CaQuiSomRoute,
  CaRolsOcultsRoute: CaRolsOcultsRoute,
  CaTermesRoute: CaTermesRoute,
  CaTornejosRoute: CaTornejosRoute,
  EnAboutRoute: EnAboutRoute,
  EnActivitiesRoute: EnActivitiesRoute,
  EnBlogRoute: EnBlogRoute,
  EnBloodOnTheClocktowerRoute: EnBloodOnTheClocktowerRoute,
  EnCatanRoute: EnCatanRoute,
  EnContactRoute: EnContactRoute,
  EnCookiesRoute: EnCookiesRoute,
  EnHiddenRolesRoute: EnHiddenRolesRoute,
  EnHowItWorksRoute: EnHowItWorksRoute,
  EnLegalNoticeRoute: EnLegalNoticeRoute,
  EnLudotecaRoute: EnLudotecaRoute,
  EnMediaRoute: EnMediaRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnTermsRoute: EnTermsRoute,
  EnTournamentsRoute: EnTournamentsRoute,
  InscripcionSlugRoute: InscripcionSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  CaIndexRoute: CaIndexRoute,
  EnIndexRoute: EnIndexRoute,
  ApiPublicRefreshMediaOgRoute: ApiPublicRefreshMediaOgRoute,
  ApiPublicSyncBggRoute: ApiPublicSyncBggRoute,
  ApiPublicUploadInviteAvatarRoute: ApiPublicUploadInviteAvatarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
